apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mud-world-ingress-http
  namespace: mud-world
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`10.0.0.17`) && PathPrefix(`/api`)
    kind: Rule
    services:
    - name: game-server
      port: 8080
  - match: Host(`10.0.0.17`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: frontend
      port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mud-world-ingress-https
  namespace: mud-world
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`10.0.0.17`) && PathPrefix(`/api`)
    kind: Rule
    services:
    - name: game-server
      port: 8080
  - match: Host(`10.0.0.17`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: frontend
      port: 3000
  tls:
    secretName: nginx-certs
