# golangci-lint configuration for Thousand Worlds
# Install: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
# Run: golangci-lint run ./...

run:
  timeout: 5m
  tests: false
  build-tags:
    - integration

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Report suspicious constructs
    - ineffassign   # Detect ineffective assignments
    - staticcheck   # Static analysis checks
    - typecheck     # Type-check code
    - unused        # Detect unused code
    - gofmt         # Check formatting
    - goimports     # Check import ordering
    - misspell      # Find misspelled words
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - gocritic      # Comprehensive code analysis
    - revive        # Fast, configurable linter

  disable:
    - depguard      # We have many dependencies
    - funlen        # Some functions are legitimately long
    - gochecknoglobals # We use package-level vars for configs

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - shadow  # Too many false positives

  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - checkPrivateReceivers
          - sayRepetitiveInsteadOfStutters

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam  # We pass some large structs by value intentionally

  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gocritic
        - unparam

    # Exclude generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all

  max-issues-per-linter: 50
  max-same-issues: 10
