// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/simulation_events.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HeightmapDelta tracks incremental changes to terrain
// Used for efficient delta streaming instead of full snapshots
type HeightmapDelta struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Year                 int64                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`                                                                // Simulation year when delta was recorded
	Resolution           int32                  `protobuf:"varint,2,opt,name=resolution,proto3" json:"resolution,omitempty"`                                                    // Grid resolution (per face)
	Cells                []*CellDelta           `protobuf:"bytes,3,rep,name=cells,proto3" json:"cells,omitempty"`                                                               // Changed cells only
	TotalElevationChange float64                `protobuf:"fixed64,4,opt,name=total_elevation_change,json=totalElevationChange,proto3" json:"total_elevation_change,omitempty"` // Sum of all elevation changes
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HeightmapDelta) Reset() {
	*x = HeightmapDelta{}
	mi := &file_api_proto_simulation_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeightmapDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeightmapDelta) ProtoMessage() {}

func (x *HeightmapDelta) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simulation_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeightmapDelta.ProtoReflect.Descriptor instead.
func (*HeightmapDelta) Descriptor() ([]byte, []int) {
	return file_api_proto_simulation_events_proto_rawDescGZIP(), []int{0}
}

func (x *HeightmapDelta) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *HeightmapDelta) GetResolution() int32 {
	if x != nil {
		return x.Resolution
	}
	return 0
}

func (x *HeightmapDelta) GetCells() []*CellDelta {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *HeightmapDelta) GetTotalElevationChange() float64 {
	if x != nil {
		return x.TotalElevationChange
	}
	return 0
}

// CellDelta represents a single cell's change
type CellDelta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Face           int32                  `protobuf:"varint,1,opt,name=face,proto3" json:"face,omitempty"`                                            // Cube face (0-5)
	X              int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`                                                  // X coordinate on face
	Y              int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`                                                  // Y coordinate on face
	ElevationDelta float64                `protobuf:"fixed64,4,opt,name=elevation_delta,json=elevationDelta,proto3" json:"elevation_delta,omitempty"` // Change in meters
	SedimentDelta  float64                `protobuf:"fixed64,5,opt,name=sediment_delta,json=sedimentDelta,proto3" json:"sediment_delta,omitempty"`    // Change in sediment depth
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CellDelta) Reset() {
	*x = CellDelta{}
	mi := &file_api_proto_simulation_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellDelta) ProtoMessage() {}

func (x *CellDelta) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simulation_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellDelta.ProtoReflect.Descriptor instead.
func (*CellDelta) Descriptor() ([]byte, []int) {
	return file_api_proto_simulation_events_proto_rawDescGZIP(), []int{1}
}

func (x *CellDelta) GetFace() int32 {
	if x != nil {
		return x.Face
	}
	return 0
}

func (x *CellDelta) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CellDelta) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *CellDelta) GetElevationDelta() float64 {
	if x != nil {
		return x.ElevationDelta
	}
	return 0
}

func (x *CellDelta) GetSedimentDelta() float64 {
	if x != nil {
		return x.SedimentDelta
	}
	return 0
}

// PlateDelta captures plate state for tectonic events
type PlateDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlateId       string                 `protobuf:"bytes,1,opt,name=plate_id,json=plateId,proto3" json:"plate_id,omitempty"`
	PlateType     string                 `protobuf:"bytes,2,opt,name=plate_type,json=plateType,proto3" json:"plate_type,omitempty"`   // "continental" or "oceanic"
	PositionX     float64                `protobuf:"fixed64,3,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"` // Unit sphere position
	PositionY     float64                `protobuf:"fixed64,4,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	PositionZ     float64                `protobuf:"fixed64,5,opt,name=position_z,json=positionZ,proto3" json:"position_z,omitempty"`
	VelocityX     float64                `protobuf:"fixed64,6,opt,name=velocity_x,json=velocityX,proto3" json:"velocity_x,omitempty"` // Movement direction
	VelocityY     float64                `protobuf:"fixed64,7,opt,name=velocity_y,json=velocityY,proto3" json:"velocity_y,omitempty"`
	VelocityZ     float64                `protobuf:"fixed64,8,opt,name=velocity_z,json=velocityZ,proto3" json:"velocity_z,omitempty"`
	AgeMyr        float64                `protobuf:"fixed64,9,opt,name=age_myr,json=ageMyr,proto3" json:"age_myr,omitempty"` // Age in million years
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlateDelta) Reset() {
	*x = PlateDelta{}
	mi := &file_api_proto_simulation_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlateDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlateDelta) ProtoMessage() {}

func (x *PlateDelta) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simulation_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlateDelta.ProtoReflect.Descriptor instead.
func (*PlateDelta) Descriptor() ([]byte, []int) {
	return file_api_proto_simulation_events_proto_rawDescGZIP(), []int{2}
}

func (x *PlateDelta) GetPlateId() string {
	if x != nil {
		return x.PlateId
	}
	return ""
}

func (x *PlateDelta) GetPlateType() string {
	if x != nil {
		return x.PlateType
	}
	return ""
}

func (x *PlateDelta) GetPositionX() float64 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *PlateDelta) GetPositionY() float64 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *PlateDelta) GetPositionZ() float64 {
	if x != nil {
		return x.PositionZ
	}
	return 0
}

func (x *PlateDelta) GetVelocityX() float64 {
	if x != nil {
		return x.VelocityX
	}
	return 0
}

func (x *PlateDelta) GetVelocityY() float64 {
	if x != nil {
		return x.VelocityY
	}
	return 0
}

func (x *PlateDelta) GetVelocityZ() float64 {
	if x != nil {
		return x.VelocityZ
	}
	return 0
}

func (x *PlateDelta) GetAgeMyr() float64 {
	if x != nil {
		return x.AgeMyr
	}
	return 0
}

// TectonicUpdate emitted after plate movements
// TIMING: Adaptive based on planetary heat (100K-10M years)
type TectonicUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int64                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	WorldId       string                 `protobuf:"bytes,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Plates        []*PlateDelta          `protobuf:"bytes,3,rep,name=plates,proto3" json:"plates,omitempty"`
	BoundaryCount int32                  `protobuf:"varint,4,opt,name=boundary_count,json=boundaryCount,proto3" json:"boundary_count,omitempty"`
	PlanetaryHeat float64                `protobuf:"fixed64,5,opt,name=planetary_heat,json=planetaryHeat,proto3" json:"planetary_heat,omitempty"` // Current heat multiplier (1.0-10.0)
	IntervalYears int64                  `protobuf:"varint,6,opt,name=interval_years,json=intervalYears,proto3" json:"interval_years,omitempty"`  // Years since last event (for replay)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TectonicUpdate) Reset() {
	*x = TectonicUpdate{}
	mi := &file_api_proto_simulation_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TectonicUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TectonicUpdate) ProtoMessage() {}

func (x *TectonicUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simulation_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TectonicUpdate.ProtoReflect.Descriptor instead.
func (*TectonicUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_simulation_events_proto_rawDescGZIP(), []int{3}
}

func (x *TectonicUpdate) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *TectonicUpdate) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *TectonicUpdate) GetPlates() []*PlateDelta {
	if x != nil {
		return x.Plates
	}
	return nil
}

func (x *TectonicUpdate) GetBoundaryCount() int32 {
	if x != nil {
		return x.BoundaryCount
	}
	return 0
}

func (x *TectonicUpdate) GetPlanetaryHeat() float64 {
	if x != nil {
		return x.PlanetaryHeat
	}
	return 0
}

func (x *TectonicUpdate) GetIntervalYears() int64 {
	if x != nil {
		return x.IntervalYears
	}
	return 0
}

// ErosionUpdate emitted after erosion cycles
// TIMING: Static 10M year intervals (only runs when heat <= 4.0)
type ErosionUpdate struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Year               int64                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	WorldId            string                 `protobuf:"bytes,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Delta              *HeightmapDelta        `protobuf:"bytes,3,opt,name=delta,proto3" json:"delta,omitempty"`
	AvgElevationChange float64                `protobuf:"fixed64,4,opt,name=avg_elevation_change,json=avgElevationChange,proto3" json:"avg_elevation_change,omitempty"`
	RiversUpdated      int32                  `protobuf:"varint,5,opt,name=rivers_updated,json=riversUpdated,proto3" json:"rivers_updated,omitempty"`
	LakesCount         int32                  `protobuf:"varint,6,opt,name=lakes_count,json=lakesCount,proto3" json:"lakes_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ErosionUpdate) Reset() {
	*x = ErosionUpdate{}
	mi := &file_api_proto_simulation_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErosionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErosionUpdate) ProtoMessage() {}

func (x *ErosionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simulation_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErosionUpdate.ProtoReflect.Descriptor instead.
func (*ErosionUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_simulation_events_proto_rawDescGZIP(), []int{4}
}

func (x *ErosionUpdate) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ErosionUpdate) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *ErosionUpdate) GetDelta() *HeightmapDelta {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *ErosionUpdate) GetAvgElevationChange() float64 {
	if x != nil {
		return x.AvgElevationChange
	}
	return 0
}

func (x *ErosionUpdate) GetRiversUpdated() int32 {
	if x != nil {
		return x.RiversUpdated
	}
	return 0
}

func (x *ErosionUpdate) GetLakesCount() int32 {
	if x != nil {
		return x.LakesCount
	}
	return 0
}

// PhaseTransition for major planetary events
// TIMING: Event-driven (occurs when conditions are met)
type PhaseTransition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Year           int64                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	WorldId        string                 `protobuf:"bytes,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	EventType      string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "GreatDeluge", "IceAge", "VolcanicWinter", etc.
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	SeaLevelBefore float64                `protobuf:"fixed64,5,opt,name=sea_level_before,json=seaLevelBefore,proto3" json:"sea_level_before,omitempty"`
	SeaLevelAfter  float64                `protobuf:"fixed64,6,opt,name=sea_level_after,json=seaLevelAfter,proto3" json:"sea_level_after,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PhaseTransition) Reset() {
	*x = PhaseTransition{}
	mi := &file_api_proto_simulation_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseTransition) ProtoMessage() {}

func (x *PhaseTransition) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simulation_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseTransition.ProtoReflect.Descriptor instead.
func (*PhaseTransition) Descriptor() ([]byte, []int) {
	return file_api_proto_simulation_events_proto_rawDescGZIP(), []int{5}
}

func (x *PhaseTransition) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *PhaseTransition) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *PhaseTransition) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PhaseTransition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PhaseTransition) GetSeaLevelBefore() float64 {
	if x != nil {
		return x.SeaLevelBefore
	}
	return 0
}

func (x *PhaseTransition) GetSeaLevelAfter() float64 {
	if x != nil {
		return x.SeaLevelAfter
	}
	return 0
}

// VolcanicEvent for hotspot and magma chamber eruptions
// TIMING: Adaptive based on planetary heat
type VolcanicEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int64                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	WorldId       string                 `protobuf:"bytes,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	EruptionType  string                 `protobuf:"bytes,3,opt,name=eruption_type,json=eruptionType,proto3" json:"eruption_type,omitempty"` // "hotspot", "boundary", "flood_basalt"
	LocationX     float64                `protobuf:"fixed64,4,opt,name=location_x,json=locationX,proto3" json:"location_x,omitempty"`
	LocationY     float64                `protobuf:"fixed64,5,opt,name=location_y,json=locationY,proto3" json:"location_y,omitempty"`
	LocationZ     float64                `protobuf:"fixed64,6,opt,name=location_z,json=locationZ,proto3" json:"location_z,omitempty"`
	HeightAdded   float64                `protobuf:"fixed64,7,opt,name=height_added,json=heightAdded,proto3" json:"height_added,omitempty"` // Meters of volcanic material
	Radius        float64                `protobuf:"fixed64,8,opt,name=radius,proto3" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolcanicEvent) Reset() {
	*x = VolcanicEvent{}
	mi := &file_api_proto_simulation_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolcanicEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolcanicEvent) ProtoMessage() {}

func (x *VolcanicEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simulation_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolcanicEvent.ProtoReflect.Descriptor instead.
func (*VolcanicEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_simulation_events_proto_rawDescGZIP(), []int{6}
}

func (x *VolcanicEvent) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *VolcanicEvent) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *VolcanicEvent) GetEruptionType() string {
	if x != nil {
		return x.EruptionType
	}
	return ""
}

func (x *VolcanicEvent) GetLocationX() float64 {
	if x != nil {
		return x.LocationX
	}
	return 0
}

func (x *VolcanicEvent) GetLocationY() float64 {
	if x != nil {
		return x.LocationY
	}
	return 0
}

func (x *VolcanicEvent) GetLocationZ() float64 {
	if x != nil {
		return x.LocationZ
	}
	return 0
}

func (x *VolcanicEvent) GetHeightAdded() float64 {
	if x != nil {
		return x.HeightAdded
	}
	return 0
}

func (x *VolcanicEvent) GetRadius() float64 {
	if x != nil {
		return x.Radius
	}
	return 0
}

// AtmosphereUpdate for atmospheric composition changes
// TIMING: Static (every simulation step, but only changes at era boundaries)
type AtmosphereUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int64                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	WorldId       string                 `protobuf:"bytes,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	O2Percent     float64                `protobuf:"fixed64,3,opt,name=o2_percent,json=o2Percent,proto3" json:"o2_percent,omitempty"`
	Co2Percent    float64                `protobuf:"fixed64,4,opt,name=co2_percent,json=co2Percent,proto3" json:"co2_percent,omitempty"`
	N2Percent     float64                `protobuf:"fixed64,5,opt,name=n2_percent,json=n2Percent,proto3" json:"n2_percent,omitempty"`
	Ch4Percent    float64                `protobuf:"fixed64,6,opt,name=ch4_percent,json=ch4Percent,proto3" json:"ch4_percent,omitempty"`
	Era           string                 `protobuf:"bytes,7,opt,name=era,proto3" json:"era,omitempty"` // "hadean", "archean", "proterozoic", etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtmosphereUpdate) Reset() {
	*x = AtmosphereUpdate{}
	mi := &file_api_proto_simulation_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtmosphereUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtmosphereUpdate) ProtoMessage() {}

func (x *AtmosphereUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simulation_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtmosphereUpdate.ProtoReflect.Descriptor instead.
func (*AtmosphereUpdate) Descriptor() ([]byte, []int) {
	return file_api_proto_simulation_events_proto_rawDescGZIP(), []int{7}
}

func (x *AtmosphereUpdate) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *AtmosphereUpdate) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *AtmosphereUpdate) GetO2Percent() float64 {
	if x != nil {
		return x.O2Percent
	}
	return 0
}

func (x *AtmosphereUpdate) GetCo2Percent() float64 {
	if x != nil {
		return x.Co2Percent
	}
	return 0
}

func (x *AtmosphereUpdate) GetN2Percent() float64 {
	if x != nil {
		return x.N2Percent
	}
	return 0
}

func (x *AtmosphereUpdate) GetCh4Percent() float64 {
	if x != nil {
		return x.Ch4Percent
	}
	return 0
}

func (x *AtmosphereUpdate) GetEra() string {
	if x != nil {
		return x.Era
	}
	return ""
}

// HeightmapSnapshot for periodic full state persistence
// TIMING: Static 100M year intervals OR on-demand
type HeightmapSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int64                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	WorldId       string                 `protobuf:"bytes,2,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	Resolution    int32                  `protobuf:"varint,3,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                                         // Gzip-compressed elevation array (float64[])
	EventSequence int64                  `protobuf:"varint,5,opt,name=event_sequence,json=eventSequence,proto3" json:"event_sequence,omitempty"` // NATS sequence for replay alignment
	SnapshotUrl   string                 `protobuf:"bytes,6,opt,name=snapshot_url,json=snapshotUrl,proto3" json:"snapshot_url,omitempty"`        // MinIO URL for large snapshots (if offloaded)
	// Metadata for crash recovery
	SeaLevel                 float64 `protobuf:"fixed64,7,opt,name=sea_level,json=seaLevel,proto3" json:"sea_level,omitempty"`
	TotalEventsSinceSnapshot int64   `protobuf:"varint,8,opt,name=total_events_since_snapshot,json=totalEventsSinceSnapshot,proto3" json:"total_events_since_snapshot,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HeightmapSnapshot) Reset() {
	*x = HeightmapSnapshot{}
	mi := &file_api_proto_simulation_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeightmapSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeightmapSnapshot) ProtoMessage() {}

func (x *HeightmapSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simulation_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeightmapSnapshot.ProtoReflect.Descriptor instead.
func (*HeightmapSnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_simulation_events_proto_rawDescGZIP(), []int{8}
}

func (x *HeightmapSnapshot) GetYear() int64 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *HeightmapSnapshot) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *HeightmapSnapshot) GetResolution() int32 {
	if x != nil {
		return x.Resolution
	}
	return 0
}

func (x *HeightmapSnapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HeightmapSnapshot) GetEventSequence() int64 {
	if x != nil {
		return x.EventSequence
	}
	return 0
}

func (x *HeightmapSnapshot) GetSnapshotUrl() string {
	if x != nil {
		return x.SnapshotUrl
	}
	return ""
}

func (x *HeightmapSnapshot) GetSeaLevel() float64 {
	if x != nil {
		return x.SeaLevel
	}
	return 0
}

func (x *HeightmapSnapshot) GetTotalEventsSinceSnapshot() int64 {
	if x != nil {
		return x.TotalEventsSinceSnapshot
	}
	return 0
}

// SimulationEvent wraps all event types for unified streaming
type SimulationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnix int64                  `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"` // Unix timestamp of emission
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`                                // Monotonic sequence number per world
	// Types that are valid to be assigned to Event:
	//
	//	*SimulationEvent_Tectonic
	//	*SimulationEvent_Erosion
	//	*SimulationEvent_Phase
	//	*SimulationEvent_Volcanic
	//	*SimulationEvent_Atmosphere
	//	*SimulationEvent_Snapshot
	Event         isSimulationEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationEvent) Reset() {
	*x = SimulationEvent{}
	mi := &file_api_proto_simulation_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationEvent) ProtoMessage() {}

func (x *SimulationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simulation_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationEvent.ProtoReflect.Descriptor instead.
func (*SimulationEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_simulation_events_proto_rawDescGZIP(), []int{9}
}

func (x *SimulationEvent) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *SimulationEvent) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SimulationEvent) GetEvent() isSimulationEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SimulationEvent) GetTectonic() *TectonicUpdate {
	if x != nil {
		if x, ok := x.Event.(*SimulationEvent_Tectonic); ok {
			return x.Tectonic
		}
	}
	return nil
}

func (x *SimulationEvent) GetErosion() *ErosionUpdate {
	if x != nil {
		if x, ok := x.Event.(*SimulationEvent_Erosion); ok {
			return x.Erosion
		}
	}
	return nil
}

func (x *SimulationEvent) GetPhase() *PhaseTransition {
	if x != nil {
		if x, ok := x.Event.(*SimulationEvent_Phase); ok {
			return x.Phase
		}
	}
	return nil
}

func (x *SimulationEvent) GetVolcanic() *VolcanicEvent {
	if x != nil {
		if x, ok := x.Event.(*SimulationEvent_Volcanic); ok {
			return x.Volcanic
		}
	}
	return nil
}

func (x *SimulationEvent) GetAtmosphere() *AtmosphereUpdate {
	if x != nil {
		if x, ok := x.Event.(*SimulationEvent_Atmosphere); ok {
			return x.Atmosphere
		}
	}
	return nil
}

func (x *SimulationEvent) GetSnapshot() *HeightmapSnapshot {
	if x != nil {
		if x, ok := x.Event.(*SimulationEvent_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

type isSimulationEvent_Event interface {
	isSimulationEvent_Event()
}

type SimulationEvent_Tectonic struct {
	Tectonic *TectonicUpdate `protobuf:"bytes,10,opt,name=tectonic,proto3,oneof"`
}

type SimulationEvent_Erosion struct {
	Erosion *ErosionUpdate `protobuf:"bytes,11,opt,name=erosion,proto3,oneof"`
}

type SimulationEvent_Phase struct {
	Phase *PhaseTransition `protobuf:"bytes,12,opt,name=phase,proto3,oneof"`
}

type SimulationEvent_Volcanic struct {
	Volcanic *VolcanicEvent `protobuf:"bytes,13,opt,name=volcanic,proto3,oneof"`
}

type SimulationEvent_Atmosphere struct {
	Atmosphere *AtmosphereUpdate `protobuf:"bytes,14,opt,name=atmosphere,proto3,oneof"`
}

type SimulationEvent_Snapshot struct {
	Snapshot *HeightmapSnapshot `protobuf:"bytes,15,opt,name=snapshot,proto3,oneof"`
}

func (*SimulationEvent_Tectonic) isSimulationEvent_Event() {}

func (*SimulationEvent_Erosion) isSimulationEvent_Event() {}

func (*SimulationEvent_Phase) isSimulationEvent_Event() {}

func (*SimulationEvent_Volcanic) isSimulationEvent_Event() {}

func (*SimulationEvent_Atmosphere) isSimulationEvent_Event() {}

func (*SimulationEvent_Snapshot) isSimulationEvent_Event() {}

// ReplayRequest for time manipulation
type ReplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorldId       string                 `protobuf:"bytes,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	TargetYear    int64                  `protobuf:"varint,2,opt,name=target_year,json=targetYear,proto3" json:"target_year,omitempty"`       // Year to replay to
	FromSequence  int64                  `protobuf:"varint,3,opt,name=from_sequence,json=fromSequence,proto3" json:"from_sequence,omitempty"` // Start from this event sequence
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRequest) Reset() {
	*x = ReplayRequest{}
	mi := &file_api_proto_simulation_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRequest) ProtoMessage() {}

func (x *ReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simulation_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRequest.ProtoReflect.Descriptor instead.
func (*ReplayRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_simulation_events_proto_rawDescGZIP(), []int{10}
}

func (x *ReplayRequest) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *ReplayRequest) GetTargetYear() int64 {
	if x != nil {
		return x.TargetYear
	}
	return 0
}

func (x *ReplayRequest) GetFromSequence() int64 {
	if x != nil {
		return x.FromSequence
	}
	return 0
}

// ReplayState for resuming simulation
type ReplayState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorldId        string                 `protobuf:"bytes,1,opt,name=world_id,json=worldId,proto3" json:"world_id,omitempty"`
	CurrentYear    int64                  `protobuf:"varint,2,opt,name=current_year,json=currentYear,proto3" json:"current_year,omitempty"`
	LastSequence   int64                  `protobuf:"varint,3,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"`
	SnapshotUrl    string                 `protobuf:"bytes,4,opt,name=snapshot_url,json=snapshotUrl,proto3" json:"snapshot_url,omitempty"`             // Last full snapshot
	EventsToReplay int32                  `protobuf:"varint,5,opt,name=events_to_replay,json=eventsToReplay,proto3" json:"events_to_replay,omitempty"` // Number of events after snapshot
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplayState) Reset() {
	*x = ReplayState{}
	mi := &file_api_proto_simulation_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayState) ProtoMessage() {}

func (x *ReplayState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_simulation_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayState.ProtoReflect.Descriptor instead.
func (*ReplayState) Descriptor() ([]byte, []int) {
	return file_api_proto_simulation_events_proto_rawDescGZIP(), []int{11}
}

func (x *ReplayState) GetWorldId() string {
	if x != nil {
		return x.WorldId
	}
	return ""
}

func (x *ReplayState) GetCurrentYear() int64 {
	if x != nil {
		return x.CurrentYear
	}
	return 0
}

func (x *ReplayState) GetLastSequence() int64 {
	if x != nil {
		return x.LastSequence
	}
	return 0
}

func (x *ReplayState) GetSnapshotUrl() string {
	if x != nil {
		return x.SnapshotUrl
	}
	return ""
}

func (x *ReplayState) GetEventsToReplay() int32 {
	if x != nil {
		return x.EventsToReplay
	}
	return 0
}

var File_api_proto_simulation_events_proto protoreflect.FileDescriptor

const file_api_proto_simulation_events_proto_rawDesc = "" +
	"\n" +
	"!api/proto/simulation_events.proto\x12\rsimulation.v1\"\xaa\x01\n" +
	"\x0eHeightmapDelta\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x03R\x04year\x12\x1e\n" +
	"\n" +
	"resolution\x18\x02 \x01(\x05R\n" +
	"resolution\x12.\n" +
	"\x05cells\x18\x03 \x03(\v2\x18.simulation.v1.CellDeltaR\x05cells\x124\n" +
	"\x16total_elevation_change\x18\x04 \x01(\x01R\x14totalElevationChange\"\x8b\x01\n" +
	"\tCellDelta\x12\x12\n" +
	"\x04face\x18\x01 \x01(\x05R\x04face\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12'\n" +
	"\x0felevation_delta\x18\x04 \x01(\x01R\x0eelevationDelta\x12%\n" +
	"\x0esediment_delta\x18\x05 \x01(\x01R\rsedimentDelta\"\x99\x02\n" +
	"\n" +
	"PlateDelta\x12\x19\n" +
	"\bplate_id\x18\x01 \x01(\tR\aplateId\x12\x1d\n" +
	"\n" +
	"plate_type\x18\x02 \x01(\tR\tplateType\x12\x1d\n" +
	"\n" +
	"position_x\x18\x03 \x01(\x01R\tpositionX\x12\x1d\n" +
	"\n" +
	"position_y\x18\x04 \x01(\x01R\tpositionY\x12\x1d\n" +
	"\n" +
	"position_z\x18\x05 \x01(\x01R\tpositionZ\x12\x1d\n" +
	"\n" +
	"velocity_x\x18\x06 \x01(\x01R\tvelocityX\x12\x1d\n" +
	"\n" +
	"velocity_y\x18\a \x01(\x01R\tvelocityY\x12\x1d\n" +
	"\n" +
	"velocity_z\x18\b \x01(\x01R\tvelocityZ\x12\x17\n" +
	"\aage_myr\x18\t \x01(\x01R\x06ageMyr\"\xe7\x01\n" +
	"\x0eTectonicUpdate\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x03R\x04year\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\tR\aworldId\x121\n" +
	"\x06plates\x18\x03 \x03(\v2\x19.simulation.v1.PlateDeltaR\x06plates\x12%\n" +
	"\x0eboundary_count\x18\x04 \x01(\x05R\rboundaryCount\x12%\n" +
	"\x0eplanetary_heat\x18\x05 \x01(\x01R\rplanetaryHeat\x12%\n" +
	"\x0einterval_years\x18\x06 \x01(\x03R\rintervalYears\"\xed\x01\n" +
	"\rErosionUpdate\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x03R\x04year\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\tR\aworldId\x123\n" +
	"\x05delta\x18\x03 \x01(\v2\x1d.simulation.v1.HeightmapDeltaR\x05delta\x120\n" +
	"\x14avg_elevation_change\x18\x04 \x01(\x01R\x12avgElevationChange\x12%\n" +
	"\x0erivers_updated\x18\x05 \x01(\x05R\rriversUpdated\x12\x1f\n" +
	"\vlakes_count\x18\x06 \x01(\x05R\n" +
	"lakesCount\"\xd3\x01\n" +
	"\x0fPhaseTransition\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x03R\x04year\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\tR\aworldId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12(\n" +
	"\x10sea_level_before\x18\x05 \x01(\x01R\x0eseaLevelBefore\x12&\n" +
	"\x0fsea_level_after\x18\x06 \x01(\x01R\rseaLevelAfter\"\xfb\x01\n" +
	"\rVolcanicEvent\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x03R\x04year\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\tR\aworldId\x12#\n" +
	"\reruption_type\x18\x03 \x01(\tR\feruptionType\x12\x1d\n" +
	"\n" +
	"location_x\x18\x04 \x01(\x01R\tlocationX\x12\x1d\n" +
	"\n" +
	"location_y\x18\x05 \x01(\x01R\tlocationY\x12\x1d\n" +
	"\n" +
	"location_z\x18\x06 \x01(\x01R\tlocationZ\x12!\n" +
	"\fheight_added\x18\a \x01(\x01R\vheightAdded\x12\x16\n" +
	"\x06radius\x18\b \x01(\x01R\x06radius\"\xd3\x01\n" +
	"\x10AtmosphereUpdate\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x03R\x04year\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\tR\aworldId\x12\x1d\n" +
	"\n" +
	"o2_percent\x18\x03 \x01(\x01R\to2Percent\x12\x1f\n" +
	"\vco2_percent\x18\x04 \x01(\x01R\n" +
	"co2Percent\x12\x1d\n" +
	"\n" +
	"n2_percent\x18\x05 \x01(\x01R\tn2Percent\x12\x1f\n" +
	"\vch4_percent\x18\x06 \x01(\x01R\n" +
	"ch4Percent\x12\x10\n" +
	"\x03era\x18\a \x01(\tR\x03era\"\x9c\x02\n" +
	"\x11HeightmapSnapshot\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x03R\x04year\x12\x19\n" +
	"\bworld_id\x18\x02 \x01(\tR\aworldId\x12\x1e\n" +
	"\n" +
	"resolution\x18\x03 \x01(\x05R\n" +
	"resolution\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12%\n" +
	"\x0eevent_sequence\x18\x05 \x01(\x03R\reventSequence\x12!\n" +
	"\fsnapshot_url\x18\x06 \x01(\tR\vsnapshotUrl\x12\x1b\n" +
	"\tsea_level\x18\a \x01(\x01R\bseaLevel\x12=\n" +
	"\x1btotal_events_since_snapshot\x18\b \x01(\x03R\x18totalEventsSinceSnapshot\"\xcb\x03\n" +
	"\x0fSimulationEvent\x12%\n" +
	"\x0etimestamp_unix\x18\x01 \x01(\x03R\rtimestampUnix\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12;\n" +
	"\btectonic\x18\n" +
	" \x01(\v2\x1d.simulation.v1.TectonicUpdateH\x00R\btectonic\x128\n" +
	"\aerosion\x18\v \x01(\v2\x1c.simulation.v1.ErosionUpdateH\x00R\aerosion\x126\n" +
	"\x05phase\x18\f \x01(\v2\x1e.simulation.v1.PhaseTransitionH\x00R\x05phase\x12:\n" +
	"\bvolcanic\x18\r \x01(\v2\x1c.simulation.v1.VolcanicEventH\x00R\bvolcanic\x12A\n" +
	"\n" +
	"atmosphere\x18\x0e \x01(\v2\x1f.simulation.v1.AtmosphereUpdateH\x00R\n" +
	"atmosphere\x12>\n" +
	"\bsnapshot\x18\x0f \x01(\v2 .simulation.v1.HeightmapSnapshotH\x00R\bsnapshotB\a\n" +
	"\x05event\"p\n" +
	"\rReplayRequest\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\tR\aworldId\x12\x1f\n" +
	"\vtarget_year\x18\x02 \x01(\x03R\n" +
	"targetYear\x12#\n" +
	"\rfrom_sequence\x18\x03 \x01(\x03R\ffromSequence\"\xbd\x01\n" +
	"\vReplayState\x12\x19\n" +
	"\bworld_id\x18\x01 \x01(\tR\aworldId\x12!\n" +
	"\fcurrent_year\x18\x02 \x01(\x03R\vcurrentYear\x12#\n" +
	"\rlast_sequence\x18\x03 \x01(\x03R\flastSequence\x12!\n" +
	"\fsnapshot_url\x18\x04 \x01(\tR\vsnapshotUrl\x12(\n" +
	"\x10events_to_replay\x18\x05 \x01(\x05R\x0eeventsToReplayB\x1fZ\x1dtw-backend/internal/events/pbb\x06proto3"

var (
	file_api_proto_simulation_events_proto_rawDescOnce sync.Once
	file_api_proto_simulation_events_proto_rawDescData []byte
)

func file_api_proto_simulation_events_proto_rawDescGZIP() []byte {
	file_api_proto_simulation_events_proto_rawDescOnce.Do(func() {
		file_api_proto_simulation_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_simulation_events_proto_rawDesc), len(file_api_proto_simulation_events_proto_rawDesc)))
	})
	return file_api_proto_simulation_events_proto_rawDescData
}

var file_api_proto_simulation_events_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_simulation_events_proto_goTypes = []any{
	(*HeightmapDelta)(nil),    // 0: simulation.v1.HeightmapDelta
	(*CellDelta)(nil),         // 1: simulation.v1.CellDelta
	(*PlateDelta)(nil),        // 2: simulation.v1.PlateDelta
	(*TectonicUpdate)(nil),    // 3: simulation.v1.TectonicUpdate
	(*ErosionUpdate)(nil),     // 4: simulation.v1.ErosionUpdate
	(*PhaseTransition)(nil),   // 5: simulation.v1.PhaseTransition
	(*VolcanicEvent)(nil),     // 6: simulation.v1.VolcanicEvent
	(*AtmosphereUpdate)(nil),  // 7: simulation.v1.AtmosphereUpdate
	(*HeightmapSnapshot)(nil), // 8: simulation.v1.HeightmapSnapshot
	(*SimulationEvent)(nil),   // 9: simulation.v1.SimulationEvent
	(*ReplayRequest)(nil),     // 10: simulation.v1.ReplayRequest
	(*ReplayState)(nil),       // 11: simulation.v1.ReplayState
}
var file_api_proto_simulation_events_proto_depIdxs = []int32{
	1, // 0: simulation.v1.HeightmapDelta.cells:type_name -> simulation.v1.CellDelta
	2, // 1: simulation.v1.TectonicUpdate.plates:type_name -> simulation.v1.PlateDelta
	0, // 2: simulation.v1.ErosionUpdate.delta:type_name -> simulation.v1.HeightmapDelta
	3, // 3: simulation.v1.SimulationEvent.tectonic:type_name -> simulation.v1.TectonicUpdate
	4, // 4: simulation.v1.SimulationEvent.erosion:type_name -> simulation.v1.ErosionUpdate
	5, // 5: simulation.v1.SimulationEvent.phase:type_name -> simulation.v1.PhaseTransition
	6, // 6: simulation.v1.SimulationEvent.volcanic:type_name -> simulation.v1.VolcanicEvent
	7, // 7: simulation.v1.SimulationEvent.atmosphere:type_name -> simulation.v1.AtmosphereUpdate
	8, // 8: simulation.v1.SimulationEvent.snapshot:type_name -> simulation.v1.HeightmapSnapshot
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_simulation_events_proto_init() }
func file_api_proto_simulation_events_proto_init() {
	if File_api_proto_simulation_events_proto != nil {
		return
	}
	file_api_proto_simulation_events_proto_msgTypes[9].OneofWrappers = []any{
		(*SimulationEvent_Tectonic)(nil),
		(*SimulationEvent_Erosion)(nil),
		(*SimulationEvent_Phase)(nil),
		(*SimulationEvent_Volcanic)(nil),
		(*SimulationEvent_Atmosphere)(nil),
		(*SimulationEvent_Snapshot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_simulation_events_proto_rawDesc), len(file_api_proto_simulation_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_simulation_events_proto_goTypes,
		DependencyIndexes: file_api_proto_simulation_events_proto_depIdxs,
		MessageInfos:      file_api_proto_simulation_events_proto_msgTypes,
	}.Build()
	File_api_proto_simulation_events_proto = out.File
	file_api_proto_simulation_events_proto_goTypes = nil
	file_api_proto_simulation_events_proto_depIdxs = nil
}
