ALTER TABLE characters
ADD COLUMN orientation_x DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN orientation_y DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN orientation_z DOUBLE PRECISION NOT NULL DEFAULT 0;
